#!/bin/bash
BATTERY=$($HOME/.config/scripts/ssh-host-arm64.sh "pmset -g batt | grep % | sed -E 's/.*\t([0-9]+)%.*/\1/'")

# Exit if a battery value was not returned
if ! [[ "$BATTERY" =~ ^[0-9]+$ ]]; then
  exit 0
fi

# Battery partial
if [ "$BATTERY" -ge 90 ]; then ICON=
elif [ "$BATTERY" -ge 70 ]; then ICON=
elif [ "$BATTERY" -ge 40 ]; then ICON=
elif [ "$BATTERY" -ge 20 ]; then ICON=
else ICON=
fi

# Battery charging
CHARGING=$($HOME/.config/scripts/ssh-host-arm64.sh "pmset -g batt | grep %" | grep -Eq ' charging'; echo $?)
if [ "$CHARGING" -eq "0" ]; then
  ICON=
fi

echo $ICON $BATTERY%
echo $ICON $BATTERY%
if [ "$BATTERY" -le 10 ]; then
  echo "#FF0000"
fi

exit 0
