#!/bin/bash
VOLUME=$(~/.config/scripts/ssh-host.sh "osascript -e 'output volume of (get volume settings)'")

# Exit if an audio level was not returned
if ! [[ "$VOLUME" =~ ^[0-9]+$ ]]; then
  exit 0
fi

# Volume partial
if [ "$VOLUME" -ge 70 ]; then ICON=
elif [ "$VOLUME" -ge 30 ]; then ICON=
fi

MUTED=$(~/.config/scripts/ssh-host.sh "osascript -e 'output muted of (get volume settings)'" | grep -q false; echo $?)
if [ "$MUTED" -eq "1" ]; then
  ICON=
else
  ICON=
fi

# Show mixer on click
if [ ! -z $BLOCK_BUTTON ]; then
  # ~/.config/scripts/launch-alacritty.sh \
  #   --option window.dimensions.columns=12 \
  #   --option window.dimensions.lines=20 \
  #   --title i3bar_volume \
  #   --command zsh -c alsamixer &
  ~/.config/scripts/launch-alacritty.sh \
    --option window.dimensions.columns=108 \
    --option window.dimensions.lines=6 \
    --title i3bar_volume \
    --command zsh -c pulsemixer &
fi

echo $ICON $VOLUME%
echo $ICON $VOLUME%

exit 0
